variables:
  REMOTE: git@github.com:rakshazi/forestguild.club.git
stages:
  - build
  - deploy
  - cleanup

update progess:
  image: php:alpine
  stage: build
  only:
    - schedules
  script:
    - php updater.php update
  tags:
    - docker

build website:
  image: jekyll/jekyll
  stage: build
  only:
    - master
  before_script:
    - /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/exe/bundle || bundle update #workaround for bugged bundler
  script:
    - jekyll wowdaily
    - jekyll build
    - jekyll build #to avoid amp images bug
  after_script:
    - echo "forestguild.club" > _site/CNAME
  artifacts:
    name: pages
    paths:
      - _site/
  tags:
    - docker

deploy:
  image: alpine:latest
  stage: deploy
  only:
    - master
  before_script:
    - apk add --no-cache git openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no" > ~/.ssh/config
    - eval $(ssh-agent -s)
    - ssh-add
    - rm -rf .git
  script:
    - cd _site
    - git init
    - git remote add origin $REMOTE
    - git config user.email "me+github@rakshazi.cf"
    - git config user.name GitlabCI
    - git add --all
    - git commit -a -q -m Update
    - git push --no-thin --force origin HEAD:gh-pages
  tags:
    - docker

cleanup:
  stage: cleanup
  image: php:alpine
  only:
    - master
  except:
    - schedules
  script:
    - php updater.php cache
  tags:
    - docker
