variables:
  REMOTE: git@github.com:rakshazi/forestguild.club.git
stages:
  - data
  - build
  - deploy
  - cleanup

collect data:
  image: php:alpine
  stage: data
  before_script:
    - mkdir -p _data
  script:
    - php updater.php news
  artifacts:
    name: _data
    paths:
      - _data/
  tags:
    - docker

build website:
  image: jekyll/jekyll
  stage: build
  before_script:
    - bundle update
  script:
    - jekyll build
  after_script:
    - echo "forestguild.club" > _site/CNAME
  artifacts:
    name: pages
    paths:
      - _site/
  tags:
    - docker

deploy:
  image: alpine:latest
  stage: deploy
  before_script:
    - apk add --no-cache git openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no" > ~/.ssh/config
    - eval $(ssh-agent -s)
    - ssh-add
  script:
    - cd _site
    - git init
    - git remote add origin $REMOTE
    - git config user.email "me+github@rakshazi.cf"
    - git config user.name "Gitlab CI"
    - git add --all
    - git commit -a -q -m "CI deploy"
    - git-push git@github.com:rakshazi/forestguild.club.git gh-pages
  tags:
    - docker

cleanup:
  stage: cleanup
  image: php:alpine
  script:
    - php updater.php cache
  tags:
    - docker
