variables:
  REMOTE: git@github.com:forestguild/website.git
stages:
  - build
  - deploy

build website:
  image: jekyll/jekyll
  stage: build
  only:
    - master
  before_script:
    - bundle install
  script:
    - bundle exec jekyll updateprogress
    - bundle exec jekyll attendance --team 15620 --name main
    - bundle exec jekyll attendance --team 15829 --name static
    - bundle exec jekyll wowaffixes --region eu
    - bundle exec jekyll wowdaily
    - bundle exec jekyll build
  after_script:
    - echo "forestguild.club" > _site/CNAME
  artifacts:
    name: pages
    paths:
      - _site/
  tags:
    - docker

deploy:
  image: alpine:latest
  stage: deploy
  only:
    - master
  before_script:
    - apk add --no-cache git openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no" > ~/.ssh/config
    - eval $(ssh-agent -s)
    - ssh-add
    - rm -rf .git
  script:
    - cd _site
    - git init
    - git remote add origin $REMOTE
    - git config user.email "me+github@rakshazi.cf"
    - git config user.name GitlabCI
    - git add --all
    - git commit -a -q -m Update
    - git push --no-thin --force origin HEAD:gh-pages
  tags:
    - docker
