variables:
  REMOTE: git@github.com:rakshazi/forestguild.club.git
stages:
  - data
  - build
  - deploy
  - cleanup

collect data:
  image: php:alpine
  stage: data
  before_script:
    - mkdir -p _data
  script:
    - php updater.php news
  artifacts:
    name: _data
    paths:
      - _data/
  tags:
    - docker

build website:
  image: jekyll/jekyll
  stage: build
  before_script:
    - bundle update
  script:
    - jekyll build
  after_script:
    - echo "forestguild.club" > _site/CNAME
  artifacts:
    name: pages
    paths:
      - _site/
  tags:
    - docker

deploy:
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  before_script:
    - rm -rf .git # to avoid git "bad ref" problem
    - cd _site
    - git init
    - git remote add origin $REMOTE
    - git config user.email "me+github@rakshazi.cf"
    - git config user.name "Gitlab CI"
  script:
    - git add --all
    - git commit -a -q -m "CI deploy"
    - git-push git@github.com:rakshazi/forestguild.club.git gh-pages
  tags:
    - docker

cleanup:
  stage: cleanup
  image: php:alpine
  script:
    - php updater.php cache
  tags:
    - docker
